Repository adobe/spacecat-audit-worker, pull requests merged in 2024-08, with the labels that each got.

#346 fix: gracefully handle broken backlinks suggestion error
  src/backlinks/handler.js
  test/audits/backlinks.test.js
Labels: bug

#266 feat: verify sitemap urls
  src/sitemap/handler.js
  test/audits/sitemap.test.js
Labels: enhancement, seo

#326 feat: canonical url audit
  src/canonical/handler.js
  src/index.js
  test/audits/canonical.test.js
Labels: enhancement

#365 feat(costs): add costs audit that returns the ahrefs API units consumed and limit
  src/costs/handler.js
  src/index.js
  test/audits/costs.test.js
Labels: enhancement, automation

#360 feat: opportunities audit
  package-lock.json
  package.json
  src/index.js
  src/opportunities/opportunities.js
  test/audits/opportunities.test.js
  test/fixtures/opportunitiesdata.json
Labels: enhancement

#367 feat: introduce structured data audit
  package-lock.json
  package.json
  src/index.js
  src/structured-data/handler.js
  test/audits/structured-data.test.js
Labels: enhancement

#383 fix: audit context includes interval info
  src/cwv/handler.js
  test/audits/cwv.test.js
  test/fixtures/rum-data.js
Labels: enhancement
