Repository adobe/spacecat-audit-worker, pull requests merged in 2024-06, with the labels that each got.

#271 fix: expose traffic_domain in the broken backlinks audit data (SITES-22464)
  package-lock.json
  package.json
  test/audits/backlinks.test.js
Labels: seo

#278 feat: audit post processors
  README.md
  src/common/audit-builder.js
  src/common/audit.js
  test/common/audit.test.js
Labels: enhancement

#282 feat: rum-api-client v2 with customer specific domain key support
  package-lock.json
  package.json
  src/conversion/handler.js
  src/cwv/handler.js
  src/experimentation/handler.js
  src/notfound/handler.js
  src/support/utils.js
  test/utils/rum-utils.test.js
Labels: enhancement

#277 feat: introduce auto suggest for broken backlinks
  .nycrc.json
  package-lock.json
  package.json
  src/backlinks/handler.js
  src/support/utils.js
  test/audits/backlinks.test.js
  test/support/utils.test.js
Labels: enhancement

#285 feat: opt-out broken backlinks
  .nycrc.json
  src/backlinks/handler.js
  test/audits/backlinks.test.js
Labels: enhancement

#304 fix: use shared sqsEventAdapter
  package-lock.json
  package.json
  src/index.js
  test/index.test.js
Labels: bug
