Repository adobe/spacecat-audit-worker, pull requests merged in 2024-09, with the labels that each got.

#386 fix(cwv): audit url calculating for rum bundler API
  src/cwv/handler.js
  test/audits/cwv.test.js
Labels: bug, enhancement

#390 chore: migrate renovate secrets
  default.json
Labels: tech debt

#391 chore: renove secrets remove
  default.json
Labels: tech debt

#394 fix(deps): update dependency @adobe/spacecat-shared-ahrefs-client to v1.5.2
  package-lock.json
  package.json
  test/audits/backlinks.test.js
Labels: bug

#396 fix(broken-backlinks): introduce auto-suggest flag for broken backlinks suggestions
  src/backlinks/handler.js
  test/audits/backlinks.test.js
Labels: bug
