Repository adobe/spacecat-audit-worker, pull requests merged in 2025-01, with the labels that each got.

#552 feat: migrate to v2 data access
  .github/workflows/ci.yaml
  package-lock.json
  package.json
  src/backlinks/handler.js
  src/canonical/handler.js
  src/common/audit.js
  src/cwv/handler.js
  src/experimentation-ess/all.js
  src/experimentation-ess/common.js
  src/experimentation-opportunities/experimentation-opportunities.js
  src/internal-links/handler.js
  src/metatags/handler.js
  src/metatags/opportunityHandler.js
  src/site-detection/handler.js
  src/sitemap/handler.js
  src/structured-data/handler.js
  src/utils/data-access.js
  test/audits/backlinks.test.js
  test/audits/canonical.test.js
  test/audits/metatags.test.js
  test/audits/site-detection.test.js
  test/common/audit.test.js
  test/shared.js
  test/utils/data-access.test.js
Labels: enhancement

#587 fix: removed sendMessage for broken-backlinks
  src/backlinks/handler.js
  test/audits/backlinks.test.js
Labels: bug

#589 fix: branch protection / npm cache
  .github/actions/configure-aws/action.yaml
  .github/actions/lint-test-coverage/action.yaml
  .github/actions/setup-node-npm/action.yaml
  .github/workflows/ci.yaml
Labels: bug

#597 feat: sitemap auto-suggest
  src/sitemap/handler.js
  test/audits/sitemap.test.js
Labels: feature
