Repository adobe/spacecat-audit-worker, pull requests merged in 2025-02, with the labels that each got.

#632 fix: error propagation in handlers
  src/backlinks/handler.js
  src/common/audit.js
  src/index.js
Labels: bug

#604 feat: auto suggest for broken internal links
  README.md
  src/internal-links/handler.js
  src/internal-links/suggestions-generator.js
  test/audits/internal-links/internal-links.test.js
  test/audits/internal-links/suggestions-generator.test.js
  test/fixtures/internal-links-data.js
Labels: seo, feature

#643 refactor: attributes naming to camelCase
  src/internal-links/handler.js
  src/internal-links/suggestions-generator.js
  test/audits/internal-links/internal-links.test.js
  test/audits/internal-links/suggestions-generator.test.js
  test/fixtures/internal-links-data.js
Labels: bug

#644 fix: missing statuscodes in the sitemap audit
  src/sitemap/handler.js
  test/audits/sitemap.test.js
Labels: seo

#585 refactor: standardising opportunityAndSuggestions method
  package-lock.json
  src/backlinks/handler.js
  src/backlinks/opportunity-data-mapper.js
  src/common/opportunity.js
  src/cwv/handler.js
  src/cwv/opportunity-data-mapper.js
  src/experimentation-opportunities/handler.js
  src/experimentation-opportunities/opportunity-data-mapper.js
  src/index.js
  src/internal-links/handler.js
  src/internal-links/opportunity-data-mapper.js
  src/metatags/handler.js
  src/metatags/opportunity-data-mapper.js
  src/metatags/opportunity-handler.js
  src/notfound/handler.js
  src/sitemap/handler.js
  src/sitemap/opportunity-data-mapper.js
  src/structured-data/handler.js
  src/structured-data/opportunity-data-mapper.js
  test/audits/backlinks.test.js
  test/audits/cwv.test.js
  test/audits/experimentation-opportunities.test.js
  test/audits/internal-links/internal-links.test.js
  test/audits/metatags.test.js
  test/audits/sitemap.test.js
  test/audits/structured-data.test.js
  test/fixtures/broken-backlinks/opportunity.js
  test/fixtures/internal-links-data.js
  test/fixtures/meta-tags-data.js
  test/fixtures/structured-data/oppty.json
Labels: tech debt

#657 docs: updating README for adding Opportunities and Suggestions
  README.md
Labels: documentation

#659 feat: audit steps
  README.md
  package-lock.json
  package.json
  src/apex/handler.js
  src/canonical/handler.js
  src/common/audit-builder.js
  src/common/audit-utils.js
  src/common/base-audit.js
  src/common/index.d.ts
  src/common/index.js
  src/common/runner-audit.js
  src/common/step-audit.js
  src/cwv/handler.js
  src/experimentation-ess/all.js
  src/experimentation-ess/daily.js
  src/experimentation-opportunities/handler.js
  src/forms-opportunities/handler.js
  src/internal-links/handler.js
  src/metatags/handler.js
  src/notfound/handler.js
  src/site-detection/handler.js
  src/utils/data-access.js
  test/common/audit-utils.test.js
  test/common/audit.test.js
  test/common/step-audit.test.js
  test/shared.js
Labels: enhancement

#672 fix: step audit queue url
  package-lock.json
  package.json
  src/common/step-audit.js
  test/common/step-audit.test.js
Labels: bug

#647 feat: Alt-text audit
  src/image-alt-text/auditEngine.js
  src/image-alt-text/constants.js
  src/image-alt-text/handler.js
  src/image-alt-text/opportunityHandler.js
  src/index.js
  test/audits/image-alt-text/audit-engine.test.js
  test/audits/image-alt-text/handler.test.js
  test/audits/image-alt-text/opportunity-handler.test.js
Labels: enhancement

#620 fix: guidance high organic low ctr
  src/common/base-audit.js
  src/common/opportunity.js
  src/experimentation-opportunities/guidance-high-organic-low-ctr-handler.js
  src/experimentation-opportunities/handler.js
  src/experimentation-opportunities/opportunity-data-mapper.js
  src/index.js
  test/audits/experimentation-opportunities.test.js
  test/common/audit.test.js
  test/fixtures/experimentation-opportunities/expected-opportunities-data.json
  test/fixtures/experimentation-opportunities/experimentation-opportunity-audit.json
  test/fixtures/experimentation-opportunities/high-organic-low-ctr-guidance.json
  test/fixtures/experimentation-opportunities/opportunitiesdata.json
  test/guidance-handlers/high-organic-low-ctr.test.js
Labels: enhancement

#678 fix: chain step response
  src/common/step-audit.js
  test/common/step-audit.test.js
Labels: bug

#682 feat: unthrottle broken backlinks suggestions
  src/backlinks/handler.js
  test/audits/backlinks.test.js
Labels: enhancement

#691 fix: site's url not displaying in slack reports
  src/backlinks/handler.js
  test/audits/backlinks.test.js
Labels: bug

#695 fix: send continuation message to sqs in add step
  src/common/audit-utils.js
  test/common/audit-utils.test.js
  test/common/step-audit.test.js
Labels: bug

#687 fix: suggest lowercase version of the URL
  static/prompts/broken-backlinks.prompt
Labels: bug

#707 fix: [alt-text] reduces image batching and improves logging
  src/image-alt-text/suggestionsEngine.js
  static/prompts/image-alt-text.prompt
  test/audits/image-alt-text/suggestions-engine.test.js
Labels: bug

#709 fix: handle missing S3 contents and refine scrape file selection
  src/support/utils.js
  test/support/utils.test.js
Labels: bug

#719 fix(override-base-url): use overrideBaseURL from site.config.fetchConfig
  package-lock.json
  package.json
  src/backlinks/handler.js
Labels: enhancement
