Repository adobe/spacecat-audit-worker, pull requests merged in 2025-05, with the labels that each got.

#829 feat: Add stepped audit support for meta-tags
  src/metatags/handler.js
  test/audits/metatags.test.js
  test/fixtures/meta-tags-data.js
Labels: WIP

#862 fix: lhs timeout
  package-lock.json
  src/support/psi-client.js
Labels: bug

#870 fix: job runner and audit tests timeout
  test/common/async-job-runner.test.js
  test/common/audit.test.js
Labels: bug

#880 feat: introduce bad-links
  src/preflight/handler.js
  test/audits/preflight.test.js
Labels: enhancement

#890 fix: preflight response according to API spec
  src/preflight/handler.js
  test/audits/preflight.test.js
  test/fixtures/preflight/preflight-identify.json
  test/fixtures/preflight/preflight-suggest.json
Labels: enhancement

#904 fix: preflight canonical identify
  src/canonical/handler.js
  src/preflight/handler.js
  test/audits/preflight.test.js
  test/fixtures/preflight/preflight-identify.json
  test/fixtures/preflight/preflight-suggest.json
Labels: bug

#895 feat: add accessibility audit
  src/accessibility/handler.js
  src/accessibility/utils/constants.js
  src/accessibility/utils/data-processing.js
  src/accessibility/utils/generate-md-reports.js
  src/accessibility/utils/report-oppty.js
  src/index.js
  src/utils/s3-utils.js
  test/audits/accessibility.test.js
  test/audits/accessibility/data-processing.test.js
  test/audits/accessibility/generate-md-reports.test.js
  test/audits/accessibility/report-oppty.test.js
  test/fixtures/accessibility-data.js
Labels: enhancement
